### ISSUE TITLE
Label Original Images

### ISSUE THREAD

**Issue by synoet** [NYU-RoboSub/vision#5]

**Comment by skyekim** [comment]
First 35 original images labeled 
[classes.txt](https://github.com/NYU-RoboSub/vision/files/8366654/classes.txt)
[IMG_3046.txt](https://github.com/NYU-RoboSub/vision/files/8366655/IMG_3046.txt)
[IMG_3047.txt](https://github.com/NYU-RoboSub/vision/files/8366656/IMG_3047.txt)
[IMG_3048.txt](https://github.com/NYU-RoboSub/vision/files/8366657/IMG_3048.txt)
[IMG_3049.txt](https://github.com/NYU-RoboSub/vision/files/8366658/IMG_3049.txt)
[IMG_3050.txt](https://github.com/NYU-RoboSub/vision/files/8366659/IMG_3050.txt)
[IMG_3051.txt](https://github.com/NYU-RoboSub/vision/files/8366660/IMG_3051.txt)
[IMG_3052.txt](https://github.com/NYU-RoboSub/vision/files/8366662/IMG_3052.txt)
[IMG_3053.txt](https://github.com/NYU-RoboSub/vision/files/8366663/IMG_3053.txt)
[IMG_3054.txt](https://github.com/NYU-RoboSub/vision/files/8366664/IMG_3054.txt)
[IMG_3055.txt](https://github.com/NYU-RoboSub/vision/files/8366665/IMG_3055.txt)
[IMG_3056.txt](https://github.com/NYU-RoboSub/vision/files/8366666/IMG_3056.txt)
[IMG_3057.txt](https://github.com/NYU-RoboSub/vision/files/8366667/IMG_3057.txt)
[IMG_3058.txt](https://github.com/NYU-RoboSub/vision/files/8366668/IMG_3058.txt)
[IMG_3059.txt](https://github.com/NYU-RoboSub/vision/files/8366669/IMG_3059.txt)
[IMG_3060.txt](https://github.com/NYU-RoboSub/vision/files/8366670/IMG_3060.txt)
[IMG_3061.txt](https://github.com/NYU-RoboSub/vision/files/8366671/IMG_3061.txt)
[IMG_3063.txt](https://github.com/NYU-RoboSub/vision/files/8366672/IMG_3063.txt)
[IMG_3064.txt](https://github.com/NYU-RoboSub/vision/files/8366673/IMG_3064.txt)
[IMG_3066.txt](https://github.com/NYU-RoboSub/vision/files/8366674/IMG_3066.txt)
[IMG_3067.txt](https://github.com/NYU-RoboSub/vision/files/8366675/IMG_3067.txt)
[IMG_3068.txt](https://github.com/NYU-RoboSub/vision/files/8366676/IMG_3068.txt)
[IMG_3069.txt](https://github.com/NYU-RoboSub/vision/files/8366677/IMG_3069.txt)
[IMG_3070.txt](https://github.com/NYU-RoboSub/vision/files/8366678/IMG_3070.txt)
[IMG_3071.txt](https://github.com/NYU-RoboSub/vision/files/8366679/IMG_3071.txt)
[IMG_3072.txt](https://github.com/NYU-RoboSub/vision/files/8366680/IMG_3072.txt)
[IMG_3073.txt](https://github.com/NYU-RoboSub/vision/files/8366681/IMG_3073.txt)
[IMG_3074.txt](https://github.com/NYU-RoboSub/vision/files/8366682/IMG_3074.txt)
[IMG_3075.txt](https://github.com/NYU-RoboSub/vision/files/8366683/IMG_3075.txt)
[IMG_3076.txt](https://github.com/NYU-RoboSub/vision/files/8366684/IMG_3076.txt)
[IMG_3077.txt](https://github.com/NYU-RoboSub/vision/files/8366685/IMG_3077.txt)
[IMG_3078.txt](https://github.com/NYU-RoboSub/vision/files/8366686/IMG_3078.txt)
[IMG_3079.txt](https://github.com/NYU-RoboSub/vision/files/8366687/IMG_3079.txt)
[IMG_3080.txt](https://github.com/NYU-RoboSub/vision/files/8366688/IMG_3080.txt)
[IMG_3081.txt](https://github.com/NYU-RoboSub/vision/files/8366689/IMG_3081.txt)
[IMG_3082.txt](https://github.com/NYU-RoboSub/vision/files/8366690/IMG_3082.txt)

**Comment by Yarbhelp-bit** [comment]
The rest 45 pictures
[g-man (1).zip](https://github.com/NYU-RoboSub/vision/files/8367074/g-man.1.zip)
